version: 2
jobs:
  build:
    working_directory: ~/overtheairbrew
    docker:
      - image: 'circleci/node:16'
    environment:
      HUSKY: '0'
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/arm/v7,linux/arm64/v8,linux/amd64
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - setup_remote_docker:
          version: 20.10.2
      - checkout
      - run:
          name: install-dockerx
          command: |
            mkdir -p ~/.docker/cli-plugins
            curl -L --output ~/.docker/cli-plugins/docker-buildx "https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.linux-amd64"
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            docker buildx install
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"

            docker context create tls-environment
            docker buildx create --name multiarch-builder --driver docker-container --use tls-environment
            docker buildx inspect --bootstrap
      - run:
          name: install
          command: npm ci
      - run:
          name: release
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
            npm run semantic-release
      - persist_to_workspace:
          root: ~/overtheairbrew
          paths:
            - README.md

  push-docker-readme:
    working_directory: ~/overtheairbrew
    docker:
      - image: 'circleci/node:16'
    steps:
      - setup_remote_docker:
          version: 20.10.2
      - attach_workspace:
          at: ~/overtheairbrew
      - run:
          name: install dockerrm
          command: |
            mkdir -p ~/.docker/cli-plugins
            curl -L --output ~/.docker/cli-plugins/docker-pushrm "https://github.com/christian-korneck/docker-pushrm/releases/download/v1.8.0/docker-pushrm_linux_amd64"
            chmod a+x ~/.docker/cli-plugins/docker-pushrm
      - run:
          name: update readme
          command: |
            DOCKER_USER=$DOCKER_USERNAME DOCKER_PASS=$DOCKER_PASSWORD docker pushrm overtheairbrew/tilt-bridge

workflows:
  version: 2
  build_release:
    jobs:
      - build:
          context: OVERTHEAIR_HOMEBREW
      - push-docker-readme:
          requires: 
            - build
          context: OVERTHEAIR_HOMEBREW
          filters:
            branches:
              only:
                - master

